/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.Label;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JPanel;

/**
 *
 * @author fiat4
 */
public class menu extends javax.swing.JFrame {
  private JFrameStudent nhanvien=new JFrameStudent();
private dichvuframe hangxe=new dichvuframe();
private Thongke thongke = new Thongke();
private Hoadon hoadon= new Hoadon();
  private JFrameStudent st=new JFrameStudent();

    /**
     * Creates new form main
     */
    public menu() {  
       
        initComponents();
    


        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1HangXe = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanelNhanvien = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanelHoaDon = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanelThongKe = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanelDangXuat = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));
        setLocation(new java.awt.Point(200, 100));

        jPanel1.setBackground(new java.awt.Color(255, 194, 111));

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabel1.setText("quản lí tiệm sửa xe");

        jPanel1HangXe.setBackground(new java.awt.Color(195, 129, 84));
        jPanel1HangXe.setForeground(new java.awt.Color(0, 204, 204));
        jPanel1HangXe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1HangXeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1HangXeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1HangXeMouseExited(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\fiat4\\OneDrive\\Documents\\NetBeansProjects\\rybak\\src\\main\\java\\image\\sv.png")); // NOI18N

        javax.swing.GroupLayout jPanel1HangXeLayout = new javax.swing.GroupLayout(jPanel1HangXe);
        jPanel1HangXe.setLayout(jPanel1HangXeLayout);
        jPanel1HangXeLayout.setHorizontalGroup(
            jPanel1HangXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1HangXeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1HangXeLayout.setVerticalGroup(
            jPanel1HangXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1HangXeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jPanelNhanvien.setBackground(new java.awt.Color(195, 129, 84));
        jPanelNhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelNhanvienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelNhanvienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelNhanvienMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelNhanvienMousePressed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\fiat4\\OneDrive\\Documents\\NetBeansProjects\\rybak\\src\\main\\java\\image\\love.jpg")); // NOI18N

        javax.swing.GroupLayout jPanelNhanvienLayout = new javax.swing.GroupLayout(jPanelNhanvien);
        jPanelNhanvien.setLayout(jPanelNhanvienLayout);
        jPanelNhanvienLayout.setHorizontalGroup(
            jPanelNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNhanvienLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelNhanvienLayout.setVerticalGroup(
            jPanelNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNhanvienLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanelHoaDon.setBackground(new java.awt.Color(195, 129, 84));
        jPanelHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        jPanelHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelHoaDonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelHoaDonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelHoaDonMouseExited(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\fiat4\\OneDrive\\Documents\\NetBeansProjects\\rybak\\src\\main\\java\\image\\123.jpg")); // NOI18N

        javax.swing.GroupLayout jPanelHoaDonLayout = new javax.swing.GroupLayout(jPanelHoaDon);
        jPanelHoaDon.setLayout(jPanelHoaDonLayout);
        jPanelHoaDonLayout.setHorizontalGroup(
            jPanelHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHoaDonLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanelHoaDonLayout.setVerticalGroup(
            jPanelHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHoaDonLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanelThongKe.setBackground(new java.awt.Color(195, 129, 84));
        jPanelThongKe.setForeground(new java.awt.Color(17, 98, 50));
        jPanelThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelThongKeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelThongKeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelThongKeMouseExited(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\fiat4\\OneDrive\\Documents\\NetBeansProjects\\rybak\\src\\main\\java\\image\\tk.jpg")); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelThongKeLayout = new javax.swing.GroupLayout(jPanelThongKe);
        jPanelThongKe.setLayout(jPanelThongKeLayout);
        jPanelThongKeLayout.setHorizontalGroup(
            jPanelThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThongKeLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );
        jPanelThongKeLayout.setVerticalGroup(
            jPanelThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThongKeLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelDangXuat.setBackground(new java.awt.Color(136, 74, 57));
        jPanelDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelDangXuatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelDangXuatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelDangXuatMouseExited(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Đăng xuất");

        javax.swing.GroupLayout jPanelDangXuatLayout = new javax.swing.GroupLayout(jPanelDangXuat);
        jPanelDangXuat.setLayout(jPanelDangXuatLayout);
        jPanelDangXuatLayout.setHorizontalGroup(
            jPanelDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDangXuatLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelDangXuatLayout.setVerticalGroup(
            jPanelDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDangXuatLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(jPanelDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelNhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1HangXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jPanelDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1HangXe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(350, 350, 350))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelDangXuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDangXuatMouseExited
        jPanelDangXuat.setBackground(colorHover);
    }//GEN-LAST:event_jPanelDangXuatMouseExited

    private void jPanelDangXuatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDangXuatMouseEntered
        jPanelDangXuat.setBackground(color);
    }//GEN-LAST:event_jPanelDangXuatMouseEntered

    private void jPanelDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDangXuatMouseClicked
        loggin lg= new loggin();
        lg.setLocation(200,100);
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanelDangXuatMouseClicked

    private void jPanel1HangXeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1HangXeMouseExited
        jPanel1HangXe.setBackground(colorHover);
    }//GEN-LAST:event_jPanel1HangXeMouseExited

    private void jPanel1HangXeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1HangXeMouseEntered
        jPanel1HangXe.setBackground(color);
    }//GEN-LAST:event_jPanel1HangXeMouseEntered

    private void jPanel1HangXeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1HangXeMouseClicked
        hangxe.setLocation(200, 100);
        hangxe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel1HangXeMouseClicked

    private void jPanelThongKeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelThongKeMouseExited
        jPanelThongKe.setBackground(colorHover);
    }//GEN-LAST:event_jPanelThongKeMouseExited

    private void jPanelThongKeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelThongKeMouseEntered
        jPanelThongKe.setBackground(color);
    }//GEN-LAST:event_jPanelThongKeMouseEntered

    private void jPanelThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelThongKeMouseClicked
      thongke.setLocation(200, 100);
        thongke.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanelThongKeMouseClicked

    private void jPanelHoaDonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHoaDonMouseExited
        jPanelHoaDon.setBackground(colorHover);
    }//GEN-LAST:event_jPanelHoaDonMouseExited

    private void jPanelHoaDonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHoaDonMouseEntered
        jPanelHoaDon.setBackground(color);
    }//GEN-LAST:event_jPanelHoaDonMouseEntered

    private void jPanelHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHoaDonMouseClicked
        hoadon.setLocation(200, 100);
        hoadon.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanelHoaDonMouseClicked

    private void jPanelNhanvienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelNhanvienMousePressed

    }//GEN-LAST:event_jPanelNhanvienMousePressed

    private void jPanelNhanvienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelNhanvienMouseExited
        jPanelNhanvien.setBackground(colorHover);
    }//GEN-LAST:event_jPanelNhanvienMouseExited

    private void jPanelNhanvienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelNhanvienMouseEntered
        jPanelNhanvien.setBackground(color);

    }//GEN-LAST:event_jPanelNhanvienMouseEntered

    private void jPanelNhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelNhanvienMouseClicked
        this.dispose();
        nhanvien.setLocation(200, 100);
        nhanvien.setVisible(true);

    }//GEN-LAST:event_jPanelNhanvienMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    
    Color color=new Color(136,74,57);
      Color colorHover=new Color(195,129,84);
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    private class PanelButtonMouseAdapter extends MouseAdapter{
        JPanel panell;

        public PanelButtonMouseAdapter(JPanel panell) {
            this.panell = panell;
        }
        
       @Override
        public void mouseEntered(MouseEvent e){
            
        }
           @Override
        public void mouseExited(MouseEvent e){
            
        }
        
           @Override
        public void mousePressed(MouseEvent e){
            
        }
        
           @Override
        public void mouseReleased(MouseEvent e){
            
        }
        
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel1HangXe;
    private javax.swing.JPanel jPanelDangXuat;
    private javax.swing.JPanel jPanelHoaDon;
    private javax.swing.JPanel jPanelNhanvien;
    private javax.swing.JPanel jPanelThongKe;
    // End of variables declaration//GEN-END:variables

}
